export const LIMITS = {
  MAX_CONCURRENT_PTYS: 12,
  MAX_CONCURRENT_AGENT_RUNS: 4,
  MAX_CONCURRENT_INSTALLS: 1,
  PTY_OUTPUT_FLUSH_INTERVAL_MS: 16,
  PTY_RING_BUFFER_BYTES: 64 * 1024,
  AGENT_EVENT_RING_CAPACITY: 2048,
  KILL_TIMEOUT_MS: 5000,
  HOOK_DEDUP_TTL_MS: 30_000,
  SHELL_READY_TIMEOUT_MS: 15_000
} as const;

export type LimitKey = keyof typeof LIMITS;
