import path from 'node:path';
import type { CostRecord, DailyReportResult } from '@shared/agent';
import { readCostRecords, summarize } from './tokens';

/** Vault-relative folder where saved reports land. */
export const COST_REPORT_DIR = ['03_Resources', 'cost-reports'] as const;

function toUtcDate(d: Date | string): string {
  const dt = typeof d === 'string' ? new Date(d) : d;
  return dt.toISOString().slice(0, 10);
}

function fmtUSD(n: number): string {
  return `$${n.toFixed(4)}`;
}

function fmtInt(n: number): string {
  return n.toLocaleString('en-US');
}

interface Group {
  runIds: Set<string>;
  usd: number;
  tokens: number;
  taskId: string | null;
}

/**
 * Format a digest from an explicit record list. Pure function — used
 * directly by tests and indirectly by `generateDailyReport`.
 */
export function formatDailyReport(records: CostRecord[], date: string): string {
  const summary = summarize(records);
  const halts = records.filter((r) => r.reason === 'budget_halt').length;

  const groups = new Map<string, Group>();
  for (const r of records) {
    const key = r.taskId ?? `run:${r.runId}`;
    let g = groups.get(key);
    if (!g) {
      g = { runIds: new Set(), usd: 0, tokens: 0, taskId: r.taskId };
      groups.set(key, g);
    }
    g.runIds.add(r.runId);
    g.usd += r.estUSD;
    g.tokens += r.input + r.output;
  }
  const top = [...groups.values()].sort((a, b) => b.usd - a.usd).slice(0, 5);
  const uniqueRuns = new Set(records.map((r) => r.runId)).size;

  const lines: string[] = [];
  lines.push(`# Orbit cost report — ${date}`);
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push(`- Runs: **${uniqueRuns}**`);
  lines.push(`- Budget halts: **${halts}**`);
  lines.push(`- Input tokens: **${fmtInt(summary.tokens.in)}**`);
  lines.push(`- Output tokens: **${fmtInt(summary.tokens.out)}**`);
  lines.push(`- Cache read tokens: **${fmtInt(summary.tokens.cached)}**`);
  lines.push(`- Estimated spend: **${fmtUSD(summary.estUSD)}**`);
  lines.push(`- Source: \`${summary.source}\``);
  lines.push('');
  lines.push('## Top 5 tasks by cost');
  lines.push('');
  if (top.length === 0) {
    lines.push('_No cost records for this day._');
  } else {
    lines.push('| Task | Runs | Tokens | Est USD |');
    lines.push('| --- | ---: | ---: | ---: |');
    for (const g of top) {
      const label = g.taskId ?? [...g.runIds][0] ?? '(unknown)';
      lines.push(
        `| \`${label}\` | ${g.runIds.size} | ${fmtInt(g.tokens)} | ${fmtUSD(g.usd)} |`
      );
    }
  }
  lines.push('');
  if (halts > 0) {
    lines.push('## Halts');
    lines.push('');
    for (const r of records.filter((x) => x.reason === 'budget_halt')) {
      lines.push(
        `- \`${r.runId}\`${r.taskId ? ` (task ${r.taskId})` : ''} — ${fmtInt(r.input + r.output)} tok, ${fmtUSD(r.estUSD)} at ${r.at}`
      );
    }
    lines.push('');
  }
  lines.push(
    '_Generated by Orbit. Save this file under `03_Resources/cost-reports/` via the UI to keep it in the vault._'
  );

  return lines.join('\n') + '\n';
}

/**
 * Build a markdown digest of all cost records that landed on `date` (UTC).
 * Reads the current-month NDJSON only — at M6 scale that covers "today"
 * and any same-month backfill. The returned `path` is the target if the
 * renderer elects to save the report; no file is written here.
 */
export async function generateDailyReport(
  vaultPath: string,
  dateInput: Date | string = new Date()
): Promise<DailyReportResult> {
  const date = toUtcDate(dateInput);
  const at = new Date(`${date}T00:00:00Z`);
  const all = await readCostRecords(vaultPath, at);
  const records = all.filter((r) => r.at.slice(0, 10) === date);

  const markdown = formatDailyReport(records, date);

  const absPath = path.join(
    vaultPath,
    COST_REPORT_DIR[0],
    COST_REPORT_DIR[1],
    `${date}.md`
  );

  return { path: absPath, markdown, date };
}

